version: '3.7'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  goreplay:
    image: buger/goreplay
    network_mode: "host"
    command:
      - '--input-raw=:9090'
      - '--output-stdout'