version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v2.26.0
    container_name: prometheus
    ports:
      - "9090:9090"
    command: "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - prometheus-remote-writer

  consul-server:
    image: consul:1.9.4
    container_name: consul-server
    restart: always
    volumes:
      - ./consul:/consul/config
    ports:
      - "8500:8500"
      - "8502:8502"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -advertise 192.168.99.100"
    depends_on:
      - prometheus-grpc-server-1
      - prometheus-grpc-server-2

  fabio:
    image: fabiolb/fabio:1.5.15-go1.15.5
    container_name: fabio
    ports:
      - "9999:9999"
      - "9998:9998"
    volumes:
      - ./fabio/fabio.properties:/etc/fabio/fabio.properties
    environment:
      SERVICE_9998_TAGS: "urlprefix-/fabio"
    depends_on:
      - consul-server

  registrator:
    image: gliderlabs/registrator:master
    network_mode: host
    command: "-ip 192.168.99.100 consul://192.168.99.100:8500"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    depends_on:
      - consul-server

  prometheus-grpc-server-build:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: prometheus-grpc-server:local

  prometheus-grpc-client-build:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: prometheus-grpc-client:local

  prometheus-remote-writer:
    build:
      context: .
      dockerfile: Dockerfile.remotewrite
    image: prometheus-remote-writer:local
    container_name: prometheus-remote-writer
    ports:
      - "8082:8080"

  prometheus-grpc-server-1:
    image: prometheus-grpc-server:local
    container_name: prometheus-grpc-server-1
    ports:
      - "8080:8080"
      - "8090:8090"

  prometheus-grpc-server-2:
    image: prometheus-grpc-server:local
    container_name: prometheus-grpc-server-2
    ports:
      - "8081:8080"
      - "8091:8090"

  prometheus-grpc-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: prometheus-grpc-client:local
    container_name: prometheus-grpc-client
