// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package prometheus

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PrometheusServiceClient is the client API for PrometheusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrometheusServiceClient interface {
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (PrometheusService_GetMetricsClient, error)
}

type prometheusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrometheusServiceClient(cc grpc.ClientConnInterface) PrometheusServiceClient {
	return &prometheusServiceClient{cc}
}

func (c *prometheusServiceClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (PrometheusService_GetMetricsClient, error) {
	stream, err := c.cc.NewStream(ctx, &PrometheusService_ServiceDesc.Streams[0], "/prometheus.PrometheusService/GetMetrics", opts...)
	if err != nil {
		return nil, err
	}
	x := &prometheusServiceGetMetricsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PrometheusService_GetMetricsClient interface {
	Recv() (*TimeSeries, error)
	grpc.ClientStream
}

type prometheusServiceGetMetricsClient struct {
	grpc.ClientStream
}

func (x *prometheusServiceGetMetricsClient) Recv() (*TimeSeries, error) {
	m := new(TimeSeries)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PrometheusServiceServer is the server API for PrometheusService service.
// All implementations should embed UnimplementedPrometheusServiceServer
// for forward compatibility
type PrometheusServiceServer interface {
	GetMetrics(*GetMetricsRequest, PrometheusService_GetMetricsServer) error
}

// UnimplementedPrometheusServiceServer should be embedded to have forward compatible implementations.
type UnimplementedPrometheusServiceServer struct {
}

func (UnimplementedPrometheusServiceServer) GetMetrics(*GetMetricsRequest, PrometheusService_GetMetricsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}

// UnsafePrometheusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrometheusServiceServer will
// result in compilation errors.
type UnsafePrometheusServiceServer interface {
	mustEmbedUnimplementedPrometheusServiceServer()
}

func RegisterPrometheusServiceServer(s grpc.ServiceRegistrar, srv PrometheusServiceServer) {
	s.RegisterService(&PrometheusService_ServiceDesc, srv)
}

func _PrometheusService_GetMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PrometheusServiceServer).GetMetrics(m, &prometheusServiceGetMetricsServer{stream})
}

type PrometheusService_GetMetricsServer interface {
	Send(*TimeSeries) error
	grpc.ServerStream
}

type prometheusServiceGetMetricsServer struct {
	grpc.ServerStream
}

func (x *prometheusServiceGetMetricsServer) Send(m *TimeSeries) error {
	return x.ServerStream.SendMsg(m)
}

// PrometheusService_ServiceDesc is the grpc.ServiceDesc for PrometheusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrometheusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "prometheus.PrometheusService",
	HandlerType: (*PrometheusServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetMetrics",
			Handler:       _PrometheusService_GetMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "prometheus.proto",
}
